alpha: 1.0
batch_size: 16
dataset_path: data/mental_health_dataset.csv
epochs: 7
learning_rate: 3.0e-05
max_len: 64
patience: 3
pretrained_bert: bert-base-uncased
punc_to_class:
  '!': 4
  ',': 1
  .: 2
  ':': 5
  ;: 6
  '?': 3
  O: 0
save_path: checkpoints
seed: 42
